#!/bin/bash

# Copyright PwnWriter || METIS Linux ( metislinux.org )

remove_calamares() {
    pacman --noconfirm -Rns calamares metis-welcome metis-live-scripts && rm -rf /etc/calamares
    userdel -r artix || exit 1
}




add_doas_conf_lines() {
    local conf_file="/etc/doas.conf"
    local lines=(
        "permit persist :wheel"
        "permit nopass :audio as root cmd reboot"
        "permit nopass :audio as root cmd poweroff"
        "permit nopass :audio as root cmd zzz"
    )

    printf "%s\n" "${lines[@]}" | tee "$conf_file" >/dev/null
}

replace_getty_args() {
    local conf_file="/etc/runit/runsvdir/default/agetty-tty1/conf"
    local old_line='GETTY_ARGS="--autologin root --noclear"'
    local new_line='GETTY_ARGS="--noclear"'

    if [ -w "$conf_file" ]; then
        sed -i "s|$old_line|$new_line|" "$conf_file" || exit 1
    else
        exit 1
    fi
}



# execute
replace_getty_args
add_doas_conf_lines
remove_calamares 



