#!/bin/bash

# Copyright PwnWriter || METIS Linux ( metislinux.org )

remove_calamares(){
        pacman --noconfirm -Rcns calamares && rm -rf /etc/calamares 
        userdel  -r artix  || exit 0

}

remove_calamares
